### ISSUE TITLE
How to handle furo-data-sign-pad with clear to find out if the sign-pad (was cleared/ is empty)

### ISSUE THREAD

**Issue by MarcOmlin** [theNorstroem/FuroBaseComponents#202]
**Describe the bug**
When i clear a furo-data-sign-pad i would expect the data to be empty and not get a white image. Because i can not figure out on a white image if there is a sign or not. At least it is not that easy.

**To Reproduce**
1. Go to 'https://components.furo.pro/?t=demo-FuroDataSignPad-0'
2. Draw into first Canvas
3. Look at Discription -> encoded image of your sign.
4. Click on 'CLEAR'-Button 
5. Look at Discription -> encoded image of blank sign-pad.

**Expected behavior**
If i clear the sign-pad i would expect the data to be null or at least "" and not the data of an empty image.

** Question ** 
Do you know any other solution so i can decide server side (on the data) if there is a sign or not?

**Comment by MarcOmlin** [comment]
I've got a workaround that works for me.

I use a Hook --clear to set the data to empty-string 
```
    this._FBPAddWireHook('--clear', () => {
      this.fields.unterschrift._value = '';
    });
```
 But i would like to see this data set by the component it self. 
Maybe theres a reason why this component works like that, then im up for more information ;)

Big Thx to the team you do a great job 👍

**Comment by veith** [comment]
Makes sense on the data sign-pad
