### ISSUE TITLE
furo-snackbar-display.js

### ISSUE THREAD

**Issue by MarcOmlin** [theNorstroem/FuroBaseComponents#228]
**Describe the bug**
I would like to set a custom button-text-color from my styling.js for the furo-snackbar-display. Because actually my button-text is always yellow even then i set all the styling options from the [docs](https://components.furo.pro/?t=FuroSnackbarDisplay).

```
--snackbar-background-color | Color of background | --on-primary | #212121
-- | -- | -- | --
--snackbar-label-color | Color of label in snackbar | --primary-variant,, | #dedede
--snackbar-button-text-color | Color of button text | --secondary | #bb86fc
--snackbar-border-distance | Distance to the border of the parent element
```

**Project-Path**
packages/furo-notification/src/furo-snackbar-display.js
Lines 165-166

**Code**

```
            furo-button {
             color: var(--snackbar-button-text-color, --secondary, #bb86fc));
              --on-surface: var(--secondary);
             --surface-dark: var(--snackbar-background-color, var(--on-primary, #212121));
             --surface-light: var(--snackbar-background-color, var(--on-primary, #212121));
              margin: auto;
            }
```

**Describe the bugfix**
Line 165 looks like a error to me, maybe im wrong.
```
Original:
color: var(--snackbar-button-text-color, --secondary, #bb86fc));

Changed:
color: var(--snackbar-button-text-color, var(--secondary, #bb86fc));
```

Line 166: I because --on-surface is set for my button-text-color and i would like to use something different than ..secondary i would like this change.
```
Original:
--on-surface: var(--secondary);

Changed:
--on-surface: var(--snackbar-button-text-color, var(--secondary, #bb86fc));
```

**Comment by maltenorstroem** [comment]
The fallback case of the css style var is faulty. 
Your change is correct. `var(--snackbar-button-text-color, var(--secondary, #bb86fc));`

**Comment by MarcOmlin** [comment]
Thx for the fast response and the bugfix :+1:
