### ISSUE TITLE
Error on npm build with default service spec

### ISSUE THREAD

**Issue by MarcOmlin** [theNorstroem/FuroBaseComponents#30]
I've defined a new package in the furo.spec.conf.json named artikel.
Npm-init created the initial spec files for me.

Now the artikel.service.spec-file was created with no issues ,but the description of the "page_size" query-param has some newlines `backslash n`.

When i now start the npm build i get an error in the artikelservice.proto. Becuase of this prior newline i think the artikelservice.proto file has a multilinecomment but only the first line of the comment starts with a double-slash.

The proto-file looks like this:
![proto-issue](https://user-images.githubusercontent.com/42028916/79773460-c893ff80-8331-11ea-974e-a0b176e51b98.png)

**Comment by maltenorstroem** [comment]
Hi Marc, as a workaround, you can add a multiline comment as follows:
`"description": "Use this field to specify the maximum number of results to be returned by the server. \n    //The server may further constrain the maximum number of results returned in a single page. \n    //If the page_size is 0, the server will decide the number of results to be returned. page_size=15",`

**Comment by MarcOmlin** [comment]
I removed the comment starting with the first `\n`. This worked for me, but your workaround looks better. Thx for your input @maltenorstroem
